#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : debugpy
Version  : 1.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/e6/d8/1148a0e4ee8609a7a4a17849b5cf3bba0575211f64f48827da6c200e82b6/debugpy-1.3.0.zip
Source0  : https://files.pythonhosted.org/packages/e6/d8/1148a0e4ee8609a7a4a17849b5cf3bba0575211f64f48827da6c200e82b6/debugpy-1.3.0.zip
Summary  : An implementation of the Debug Adapter Protocol for Python
Group    : Development/Tools
License  : MIT
Requires: debugpy-python = %{version}-%{release}
Requires: debugpy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev

%description
# Parts of IPython, files from: https://github.com/ipython/ipython/tree/rel-1.0.0/IPython
# The files in this package are extracted from IPython to aid the main loop integration
# See tests_mainloop for some manually runable tests

%package python
Summary: python components for the debugpy package.
Group: Default
Requires: debugpy-python3 = %{version}-%{release}

%description python
python components for the debugpy package.


%package python3
Summary: python3 components for the debugpy package.
Group: Default
Requires: python3-core
Provides: pypi(debugpy)

%description python3
python3 components for the debugpy package.


%prep
%setup -q -n debugpy-1.3.0
cd %{_builddir}/debugpy-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625076061
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
